name: syncly
description: Sistema de sincronização independente para aplicações Flutter
version: 1.1.2
maintainer: Mauricio Duarte <prussdev@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP Client
  dio: ^5.8.0+1
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Background Tasks
  workmanager: ^0.8.0
  
  # Local Storage
  shared_preferences: ^2.5.3
  
  # UUID Generation
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# Metadados do pacote
homepage: https://github.com/MauricioPDuarte/syncly
repository: https://github.com/MauricioPDuarte/syncly
issue_tracker: https://github.com/MauricioPDuarte/syncly/issues

# Tópicos para facilitar descoberta
topics:
  - sync
  - synchronization
  - flutter
  - offline
  - background-sync

# Configurações específicas do Flutter
flutter:
  # Se houver assets específicos do sync
  # assets:
  #   - assets/icons/
  
  # Se houver fontes específicas
  # fonts:
  #   - family: SyncIcons
  #     fonts:
  #       - asset: fonts/SyncIcons.ttf